export const coffees = [
  {
    id: "yirgacheffe-kochere",
    name: "Yirgacheffe Kochere",
    country: "Ethiopia",
    countryCode: "ET",
    flag: "\u{1F1EA}\u{1F1F9}",
    region: "Gedeo Zone, SNNPR",
    altitude: "1,900m",
    roast: "Light",
    process: "Natural",
    varietal: "Heirloom",
    harvest: "Nov\u2013Jan",
    scaScore: 88.5,
    body: 3,
    badge: "Single Origin",
    description: "Jasmine and bergamot with a honey-sweet finish. Naturally processed at 1,900m altitude.",
    longDescription: "A stunning naturally processed coffee from the Kochere washing station in Yirgacheffe. Jasmine and bergamot aromatics unfold into a honey-sweet body with a clean, lingering finish. Exceptional complexity that shines in Turkish brewing \u2014 the fine grind and slow extraction reveal layers of floral and fruit character.",
    flavors: ["Jasmine", "Bergamot", "Honey", "Stone Fruit", "Citrus Zest"],
    tasting: { aroma: 9.2, acidity: 8.5, sweetness: 8.8, body: 7.0, finish: 8.7, balance: 9.0 },
    brewing: { dose: "7g", water: "65ml", heat: "Low", time: "3\u20134 min" },
    supplier: { name: "Kochere Cooperative Union", location: "Kochere, Gedeo Zone, Ethiopia", farmers: 4200, cooperatives: 34, altitude: "1,800\u20132,100m", certifications: "Fair Trade since 2008" },
    gradient: "linear-gradient(135deg, #2d1a0a, #1a0e05, #3d2510)"
  },
  {
    id: "nyeri-aa-gatomboya",
    name: "Nyeri AA Gatomboya",
    country: "Kenya",
    countryCode: "KE",
    flag: "\u{1F1F0}\u{1F1EA}",
    region: "Nyeri County",
    altitude: "1,850m",
    roast: "Medium",
    process: "Washed",
    varietal: "SL28",
    harvest: "Oct\u2013Dec",
    scaScore: 89.0,
    body: 4,
    badge: "Best Seller",
    description: "Blackcurrant and grapefruit with a wine-like body. Washed process, SL28 varietal.",
    longDescription: "A bold, wine-like cup from the Gatomboya washing station in Nyeri. The SL28 varietal delivers intense blackcurrant and grapefruit with a full, juicy body. Washed processing preserves bright acidity that cuts through the richness of Turkish brewing, creating an unforgettable cup.",
    flavors: ["Blackcurrant", "Grapefruit", "Wine", "Tomato", "Dark Chocolate"],
    tasting: { aroma: 8.8, acidity: 9.0, sweetness: 8.2, body: 8.5, finish: 8.8, balance: 8.5 },
    brewing: { dose: "7g", water: "65ml", heat: "Low", time: "3\u20134 min" },
    supplier: { name: "Gatomboya Washing Station", location: "Nyeri, Central Kenya", farmers: 1200, cooperatives: 1, altitude: "1,700\u20131,900m", certifications: "Rainforest Alliance" },
    gradient: "linear-gradient(135deg, #2d0d1a, #1a0810, #4a1525)"
  },
  {
    id: "huye-red-bourbon",
    name: "Huye Red Bourbon",
    country: "Rwanda",
    countryCode: "RW",
    flag: "\u{1F1F7}\u{1F1FC}",
    region: "Huye District, Southern Province",
    altitude: "1,700m",
    roast: "Medium",
    process: "Washed",
    varietal: "Red Bourbon",
    harvest: "Mar\u2013Jun",
    scaScore: 87.5,
    body: 5,
    badge: "New Arrival",
    description: "Peach and brown sugar with silky mouthfeel. Fully washed Red Bourbon from Huye cooperative.",
    longDescription: "Silky and luxurious, this fully washed Red Bourbon from the Huye Mountain cooperative delivers peach and brown sugar sweetness with a remarkably smooth body. The clean cup profile makes it an ideal introduction to African coffees for Turkish brewing \u2014 approachable yet complex.",
    flavors: ["Peach", "Brown Sugar", "Silky", "Caramel", "Plum"],
    tasting: { aroma: 8.5, acidity: 7.8, sweetness: 9.0, body: 8.8, finish: 8.5, balance: 9.2 },
    brewing: { dose: "7g", water: "65ml", heat: "Low", time: "3\u20134 min" },
    supplier: { name: "Huye Mountain Coffee", location: "Huye, Southern Province, Rwanda", farmers: 2800, cooperatives: 8, altitude: "1,600\u20131,800m", certifications: "Organic, Fair Trade" },
    gradient: "linear-gradient(135deg, #0d1a2d, #081018, #15254a)"
  },
  {
    id: "kilimanjaro-peaberry",
    name: "Kilimanjaro Peaberry",
    country: "Tanzania",
    countryCode: "TZ",
    flag: "\u{1F1F9}\u{1F1FF}",
    region: "Kilimanjaro Region",
    altitude: "1,600m",
    roast: "Medium-Dark",
    process: "Washed",
    varietal: "Bourbon/Typica",
    harvest: "Jul\u2013Oct",
    scaScore: 86.5,
    body: 4,
    badge: "Single Origin",
    description: "Bright acidity with dark chocolate and black tea notes. Grown on volcanic slopes at high altitude.",
    longDescription: "Grown on the volcanic slopes of Mount Kilimanjaro, this Peaberry delivers concentrated flavor \u2014 each cherry produces a single round bean instead of two flat ones. Dark chocolate and black tea dominate, with a bright acidity that lifts the cup. The volcanic soil imparts a mineral depth that shines in Turkish preparation.",
    flavors: ["Dark Chocolate", "Black Tea", "Bright", "Mineral", "Citrus"],
    tasting: { aroma: 8.2, acidity: 8.5, sweetness: 7.8, body: 8.0, finish: 8.0, balance: 8.3 },
    brewing: { dose: "7g", water: "65ml", heat: "Low", time: "3\u20134 min" },
    supplier: { name: "Kilimanjaro Plantation Ltd", location: "Moshi, Kilimanjaro, Tanzania", farmers: 800, cooperatives: 3, altitude: "1,400\u20131,800m", certifications: "UTZ Certified" },
    gradient: "linear-gradient(135deg, #1a2d0d, #0d1a08, #2d4a15)"
  },
  {
    id: "sidamo-guji-natural",
    name: "Sidamo Guji Natural",
    country: "Ethiopia",
    countryCode: "ET",
    flag: "\u{1F1EA}\u{1F1F9}",
    region: "Guji Zone, Oromia",
    altitude: "2,100m",
    roast: "Light",
    process: "Natural",
    varietal: "Heirloom",
    harvest: "Nov\u2013Jan",
    scaScore: 90.0,
    body: 3,
    badge: "Limited",
    description: "Blueberry explosion with dark chocolate undertones. Sun-dried natural process creates intense fruit-forward character.",
    longDescription: "A fruit bomb from the Guji zone. Sun-dried on raised African beds, this natural process coffee delivers an intense blueberry character backed by dark chocolate undertones. At 2,100m elevation, the slow cherry maturation concentrates sugars and creates a cup that is both wild and refined. In a cezve, the fruit notes become almost jam-like.",
    flavors: ["Blueberry", "Dark Chocolate", "Fruity", "Jam", "Wine"],
    tasting: { aroma: 9.5, acidity: 8.8, sweetness: 9.2, body: 7.5, finish: 9.0, balance: 8.8 },
    brewing: { dose: "7g", water: "65ml", heat: "Low", time: "3\u20134 min" },
    supplier: { name: "Guji Highland Cooperative", location: "Hambela, Guji Zone, Ethiopia", farmers: 3500, cooperatives: 12, altitude: "1,900\u20132,200m", certifications: "Organic" },
    gradient: "linear-gradient(135deg, #2d2d0d, #1a1a08, #4a4a15)"
  },
  {
    id: "kayanza-long-miles",
    name: "Kayanza Long Miles",
    country: "Burundi",
    countryCode: "BI",
    flag: "\u{1F1E7}\u{1F1EE}",
    region: "Kayanza Province",
    altitude: "1,800m",
    roast: "Medium",
    process: "Washed",
    varietal: "Bourbon",
    harvest: "Apr\u2013Jul",
    scaScore: 86.0,
    body: 3,
    badge: "Single Origin",
    description: "Red apple and vanilla with a clean, sweet finish. Grown by smallholders in Kayanza province.",
    longDescription: "From the Long Miles Coffee Project in Kayanza, this washed Bourbon delivers red apple sweetness and vanilla bean aromatics with a remarkably clean finish. The high-altitude terroir and meticulous washing produce a cup of exceptional clarity \u2014 every flavor note is distinct and well-defined.",
    flavors: ["Red Apple", "Vanilla", "Clean", "Honey", "Floral"],
    tasting: { aroma: 8.0, acidity: 8.2, sweetness: 8.5, body: 7.5, finish: 8.0, balance: 8.8 },
    brewing: { dose: "7g", water: "65ml", heat: "Low", time: "3\u20134 min" },
    supplier: { name: "Long Miles Coffee Project", location: "Kayanza, Kayanza Province, Burundi", farmers: 1500, cooperatives: 4, altitude: "1,700\u20131,900m", certifications: "Direct Trade" },
    gradient: "linear-gradient(135deg, #1a2d2d, #0d1a1a, #154a4a)"
  }
];

export const origins = [
  { country: "Ethiopia", flag: "\u{1F1EA}\u{1F1F9}", cooperatives: 12, regions: "Yirgacheffe \u00b7 Sidamo \u00b7 Harrar \u00b7 Guji \u00b7 Limu", desc: "The birthplace of coffee. Heirloom varietals from 1,700\u20132,200m altitude." },
  { country: "Kenya", flag: "\u{1F1F0}\u{1F1EA}", cooperatives: 5, regions: "Nyeri \u00b7 Kirinyaga \u00b7 Embu \u00b7 Murang\u2019a", desc: "SL28/SL34 varietals with bold, wine-like character." },
  { country: "Rwanda", flag: "\u{1F1F7}\u{1F1FC}", cooperatives: 4, regions: "Huye \u00b7 Nyamasheke \u00b7 Gakenke", desc: "Red Bourbon excellence. Silky body and caramel sweetness." },
  { country: "Tanzania", flag: "\u{1F1F9}\u{1F1FF}", cooperatives: 3, regions: "Kilimanjaro \u00b7 Arusha \u00b7 Mbeya", desc: "Volcanic Peaberry with chocolate and black tea complexity." },
  { country: "Burundi", flag: "\u{1F1E7}\u{1F1EE}", cooperatives: 2, regions: "Kayanza \u00b7 Ngozi", desc: "Clean, sweet cups with red apple and vanilla notes." },
  { country: "Uganda", flag: "\u{1F1FA}\u{1F1EC}", cooperatives: 2, regions: "Mount Elgon \u00b7 Rwenzori", desc: "Full-bodied with nutty, chocolatey depth." }
];
